[project]
name = "odoo-addons-oca-stock-logistics-workflow"
version = "18.0.20250219.0"
dependencies = [
    "odoo-addon-delivery_procurement_group_carrier==18.0.*",
    "odoo-addon-sale_order_global_stock_route==18.0.*",
    "odoo-addon-stock_account_product_run_fifo_hook==18.0.*",
    "odoo-addon-stock_dangerous_goods==18.0.*",
    "odoo-addon-stock_no_negative==18.0.*",
    "odoo-addon-stock_owner_restriction==18.0.*",
    "odoo-addon-stock_picking_auto_create_lot==18.0.*",
    "odoo-addon-stock_picking_backorder_strategy_cancel==18.0.*",
    "odoo-addon-stock_picking_group_by_base==18.0.*",
    "odoo-addon-stock_picking_invoice_link==18.0.*",
    "odoo-addon-stock_picking_purchase_order_link==18.0.*",
    "odoo-addon-stock_picking_return_restricted_qty==18.0.*",
    "odoo-addon-stock_picking_sale_order_link==18.0.*",
    "odoo-addon-stock_picking_show_backorder==18.0.*",
    "odoo-addon-stock_picking_show_return==18.0.*",
    "odoo-addon-stock_picking_whole_scrap==18.0.*",
    "odoo-addon-stock_split_picking==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
